package core

import "fmt"

const XMAN_MAJOR_VERSION = 1
const XMAN_MINOR_VERSION = 3
const XMAN_PATCH_VERSION = 0

var XMAN_VERSION = fmt.Sprintf("%d.%d.%d", XMAN_MAJOR_VERSION, XMAN_MINOR_VERSION, XMAN_PATCH_VERSION)
