services:
  gui:
    depends_on:
      - server
    build:
      context: ./gui
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
    ports:
      - ${PORT}:80

  database:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    build:
      context: ./server/build/package/database
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - database:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - NO_PROXY=.tsa.thlv.de,.thlv.de
    depends_on:
      database:
        condition: service_healthy
    environment:
      - TZ=Europe/Berlin
      - ORIGIN=${ORIGIN}
      - TOKEN_DAY_LIFESPAN=${TOKEN_DAY_LIFESPAN}
      - TOKEN_PRIVATE_KEY=${TOKEN_PRIVATE_KEY}
      - DELETE_ARCHIVED_PROCESSES_AFTER_DAYS=${DELETE_ARCHIVED_PROCESSES_AFTER_DAYS}
      - APPRAISAL_LEVEL=${APPRAISAL_LEVEL}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_TLS_MODE=${SMTP_TLS_MODE}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL}
      - LDAP_CONFIG=${LDAP_CONFIG}
      - LDAP_URL=${LDAP_URL}
      - LDAP_TLS_INSECURE_SKIP_VERIFY=${LDAP_TLS_INSECURE_SKIP_VERIFY}
      - LDAP_BASE_DN=${LDAP_BASE_DN}
      - LDAP_USER=${LDAP_USER}
      - LDAP_PASSWORD=${LDAP_PASSWORD}
      - LDAP_ACCESS_GROUP=${LDAP_ACCESS_GROUP}
      - LDAP_ADMIN_GROUP=${LDAP_ADMIN_GROUP}
      - ARCHIVE_TARGET=${ARCHIVE_TARGET}
      - DIMAG_SFTP_SERVER_URL=${DIMAG_SFTP_SERVER_URL}
      - DIMAG_SFTP_UPLOAD_DIR=${DIMAG_SFTP_UPLOAD_DIR}
      - DIMAG_SFTP_USER=${DIMAG_SFTP_USER}
      - DIMAG_SFTP_PASSWORD=${DIMAG_SFTP_PASSWORD}
      - DIMAG_SFTP_HOST_KEY=${DIMAG_SFTP_HOST_KEY}
      - DIMAG_CORE_SOAP_ENDPOINT=${DIMAG_CORE_SOAP_ENDPOINT}
      - DIMAG_CORE_USER=${DIMAG_CORE_USER}
      - DIMAG_CORE_PASSWORD=${DIMAG_CORE_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - BORG_ENDPOINT=${BORG_ENDPOINT}
      - XDOMEA_MAX_RECORD_OBJECT_DEPTH=${XDOMEA_MAX_RECORD_OBJECT_DEPTH}
      - INSTITUTION_NAME=${INSTITUTION_NAME}
      - INSTITUTION_ABBREVIATION=${INSTITUTION_ABBREVIATION}
    volumes:
      - message_store:/xman/message_store
      - ./data/transfer_dir:/xman/transfer_dir
      - ./data/archive:/xman/archive

  report:
    build:
      context: ./report
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - NO_PROXY=.tsa.thlv.de,.thlv.de

volumes:
  database:
  message_store:
  webdav:
