services:
  gui:
    build:
      context: ./gui
      args:
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTPS_PROXY}
        - CONFIGURATION=production

  server:
    build:
      context: ./server
      args:
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTPS_PROXY}
        - NO_PROXY=${NO_PROXY}

  report:
    build:
      context: ./report
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - NO_PROXY=${NO_PROXY}
