services:
  gui:
    depends_on:
      - server
    build:
      context: ./gui
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
    ports:
      - ${PORT}:80

  mongo:
    image: docker.io/mongo
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 1s
      timeout: 1s
      retries: 10
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - mongo:/data/db

  server:
    build:
      context: ./server
      args:
        - http_proxy=${HTTP_PROXY}
        - https_proxy=${HTTPS_PROXY}
        - NO_PROXY=${NO_PROXY}
        - UID=${UID}
        - GID=${GID}
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - TZ=Europe/Berlin
      - ORIGIN=${ORIGIN}
      - LOGIN_TOKEN_LIFETIME_DAYS=${LOGIN_TOKEN_LIFETIME_DAYS}
      - DELETE_ARCHIVED_SUBMISSIONS_AFTER_DAYS=${DELETE_ARCHIVED_SUBMISSIONS_AFTER_DAYS}
      - DELETE_ERRORS_AFTER_DAYS=${DELETE_ERRORS_AFTER_DAYS}
      - INSTITUTION_NAME=${INSTITUTION_NAME}
      - INSTITUTION_ABBREVIATION=${INSTITUTION_ABBREVIATION}
      - APPRAISAL_LEVEL=${APPRAISAL_LEVEL}
      - MAX_RECORD_DEPTH=${MAX_RECORD_DEPTH}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DB=${MONGODB_DB}
      - LDAP_CONFIG=${LDAP_CONFIG}
      - LDAP_URL=${LDAP_URL}
      - LDAP_TLS_INSECURE_SKIP_VERIFY=${LDAP_TLS_INSECURE_SKIP_VERIFY}
      - LDAP_BASE_DN=${LDAP_BASE_DN}
      - LDAP_USER=${LDAP_USER}
      - LDAP_PASSWORD=${LDAP_PASSWORD}
      - LDAP_ACCESS_GROUP=${LDAP_ACCESS_GROUP}
      - LDAP_ADMIN_GROUP=${LDAP_ADMIN_GROUP}
      - SMTP_SERVER=${SMTP_SERVER}
      - SMTP_TLS_MODE=${SMTP_TLS_MODE}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL}
      - BORG_URL=${BORG_URL}
      - ARCHIVE_TARGET=${ARCHIVE_TARGET}
      - DIMAG_SFTP_SERVER_URL=${DIMAG_SFTP_SERVER_URL}
      - DIMAG_SFTP_UPLOAD_DIR=${DIMAG_SFTP_UPLOAD_DIR}
      - DIMAG_SFTP_USER=${DIMAG_SFTP_USER}
      - DIMAG_SFTP_PASSWORD=${DIMAG_SFTP_PASSWORD}
      - DIMAG_CORE_SOAP_ENDPOINT=${DIMAG_CORE_SOAP_ENDPOINT}
      - DIMAG_CORE_USER=${DIMAG_CORE_USER}
      - DIMAG_CORE_PASSWORD=${DIMAG_CORE_PASSWORD}
    volumes:
      - message_store:/xman/message_store
      - ./data/transfer_dir:/xman/transfer_dir
      - ./data/archive:/xman/archive

  report:
    build:
      context: ./report
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - NO_PROXY=${NO_PROXY}

volumes:
  message_store:
  mongo:
