# Development additions and overrides

services:
  gui:
    build:
      args:
        - CONFIGURATION=development

  server:
    volumes:
      - ./debug-data:/debug-data
    environment:
      - DEBUG_MODE=true
      - GIN_MODE=debug
      - INIT_TEST_SETUP=true
      - TRANSFER_DIR_SCAN_INTERVAL_SECONDS=1
      - WEBDAV_USERNAME=${WEBDAV_USERNAME}
      - WEBDAV_PASSWORD=${WEBDAV_PASSWORD}
      - NO_PROXY=${NO_PROXY},webdav
    ports:
      - 3000:80
    extra_hosts:
      - host.docker.internal:host-gateway

  report:
    environment:
      - GIN_MODE=debug

  mongo-express:
    image: docker.io/mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongo:27017/
      ME_CONFIG_BASICAUTH: false

  webdav:
    image: docker.io/bytemark/webdav
    environment:
      USERNAME: ${WEBDAV_USERNAME}
      PASSWORD: ${WEBDAV_PASSWORD}
    ports:
      - 8082:80
    volumes:
      - ./data/webdav:/var/lib/dav

  # LDAP test server with default credentials
  ldap:
    image: ghcr.io/rroemhild/docker-test-openldap:master
    ulimits:
      nofile: 1024
    volumes:
      - ./data/tls/ldap.crt:/etc/ldap/ssl/ldap.crt
      - ./data/tls/ldap.key:/etc/ldap/ssl/ldap.key

  # SMTP test server with a web UI to inspect received e-mails
  mailhog:
    image: docker.io/mailhog/mailhog
    ports:
      - 8025:8025 # web ui

  # TLS wrapper for Mailhog
  mailhog-tls:
    image: docker.io/dweomer/stunnel
    environment:
      - STUNNEL_SERVICE=smtps
      - STUNNEL_ACCEPT=465
      - STUNNEL_CONNECT=mailhog:1025
    volumes:
      - ./data/tls/mailhog-tls.crt:/etc/stunnel/stunnel.pem:ro
      - ./data/tls/mailhog-tls.key:/etc/stunnel/stunnel.key:ro
