# Development additions and overrides

services:
  gui:
    build:
      args:
        - CONFIGURATION=development

  server:
    volumes:
      - ./debug-data:/debug-data
    environment:
      - DEBUG_MODE=true
      - GIN_MODE=debug
    ports:
      - 3000:80
  report:
    environment:
      - GIN_MODE=debug

  database-debug:
    image: sosedoff/pgweb
    depends_on:
      database:
        condition: service_healthy
    environment:
      - PGWEB_DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@database/${POSTGRES_DB}?sslmode=disable
    ports:
      - 8081:8081

  webdav:
    image: bytemark/webdav
    environment:
      USERNAME: ${WEBDAV_USERNAME}
      PASSWORD: ${WEBDAV_PASSWORD}
    ports:
      - 8082:80
    volumes:
      - webdav:/var/lib/dav

  # LDAP test server with default credentials
  ldap:
    image: ghcr.io/rroemhild/docker-test-openldap:master
    ulimits:
      nofile: 1024
    volumes:
      - ./data/tls/ldap.crt:/etc/ldap/ssl/ldap.crt
      - ./data/tls/ldap.key:/etc/ldap/ssl/ldap.key

  # SMTP test server with a web UI to inspect received e-mails
  mailhog:
    image: mailhog/mailhog
    ports:
      - 8025:8025 # web ui

  # TLS wrapper for Mailhog
  mailhog-tls:
    image: dweomer/stunnel
    environment:
      - STUNNEL_SERVICE=smtps
      - STUNNEL_ACCEPT=465
      - STUNNEL_CONNECT=mailhog:1025
    volumes:
      - ./data/tls/mailhog-tls.crt:/etc/stunnel/stunnel.pem:ro
      - ./data/tls/mailhog-tls.key:/etc/stunnel/stunnel.key:ro
    ports:
      - 465:465 # smtp tls
