services:
  backend:
    user: "${UID}:${GID}"
    build:
      context: ./backend
      args:
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTPS_PROXY}
        NO_PROXY: ${NO_PROXY}
    environment:
      TZ: "Europe/Berlin"
      MONGODB_URL: ${MONGODB_URL}
      MONGODB_DATABASE: ${MONGODB_DATABASE}
    volumes:
      - ./data/transfer:/app/data/transfer
  
  mongo:
    image: docker.io/mongo:8.2.6
    user: ${UID}:${GID}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - ./data/db:/data/db
    restart: unless-stopped

  mongo-express:
    image: docker.io/mongo-express
    depends_on:
      mongo:
        condition: service_healthy
        restart: true
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: ${MONGODB_URL}
      ME_CONFIG_BASICAUTH: "false"