services:
  gui:
    depends_on:
      - server
    build:
      context: ./gui
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
    ports:
      - ${PORT}:80

  database:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    build:
      context: ./server/build/package/database
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - database:/var/lib/postgresql/data

  server:
    build:
      context: ./server
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - NO_PROXY=.tsa.thlv.de,.thlv.de
    depends_on:
      database:
        condition: service_healthy
    environment:
      - TZ=Europe/Berlin
      - GIN_MODE=${GIN_MODE}
      - TOKEN_DAY_LIFESPAN=${TOKEN_DAY_LIFESPAN}
      - TOKEN_PRIVATE_KEY=${TOKEN_PRIVATE_KEY}
      - DELETE_ARCHIVED_PROCESSES_AFTER_DAYS=${DELETE_ARCHIVED_PROCESSES_AFTER_DAYS}
      - AD_URL=${AD_URL}
      - AD_BASE_DN=${AD_BASE_DN}
      - AD_USER=${AD_USER}
      - AD_PASS=${AD_PASS}
      - AD_ACCESS_GROUP=${AD_ACCESS_GROUP}
      - AD_ADMIN_GROUP=${AD_ADMIN_GROUP}
      - ARCHIVE_TARGET=${ARCHIVE_TARGET}
      - DIMAG_SFTP_SERVER_URL=${DIMAG_SFTP_SERVER_URL}
      - DIMAG_SFTP_UPLOAD_DIR=${DIMAG_SFTP_UPLOAD_DIR}
      - DIMAG_SFTP_USER=${DIMAG_SFTP_USER}
      - DIMAG_SFTP_PASSWORD=${DIMAG_SFTP_PASSWORD}
      - DIMAG_CORE_SOAP_ENDPOINT=${DIMAG_CORE_SOAP_ENDPOINT}
      - DIMAG_CORE_USER=${DIMAG_CORE_USER}
      - DIMAG_CORE_PASSWORD=${DIMAG_CORE_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - BORG_ENDPOINT=${BORG_ENDPOINT}
    volumes:
      - message_store:/xman/message_store
      - ./transfer_dir:/xman/transfer_dir
      - ./archive:/xman/archive

  report:
    build:
      context: ./report
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - NO_PROXY=.tsa.thlv.de,.thlv.de
    environment:
      - GIN_MODE=${GIN_MODE}

volumes:
  database:
  message_store:
  webdav:
