services:

  server:
    container_name: xman-server
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: dockerfile_server
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
    environment:
      - XMAN_SERVER_CONTAINER_PORT=${XMAN_SERVER_CONTAINER_PORT}
    ports:
      - ${XMAN_SERVER_HOST_PORT}:${XMAN_SERVER_CONTAINER_PORT}