package xdomea

import "fmt"

const XMAN_MAJOR_VERSION = 1
const XMAN_MINOR_VERSION = 2
const XMAN_PATCH_VERSION = 1

var XMAN_VERSION = fmt.Sprintf("%d.%d.%d", XMAN_MAJOR_VERSION, XMAN_MINOR_VERSION, XMAN_PATCH_VERSION)
